"""Primary key mixins for UUID and integer IDs."""

from uuid import UUID, uuid4

from sqlalchemy.orm import Mapped, mapped_column


class UUIDPrimaryKeyMixin:
    """Adds a UUID primary key column named ``id``.

    The column auto-generates a UUID4 value on creation.

    Example::

        class User(AutoBase, UUIDPrimaryKeyMixin):
            __tablename__ = "users"
            name: Mapped[str]

        user = User(name="alice")
        user.id  # UUID('a1b2c3d4-...')
    """

    id: Mapped[UUID] = mapped_column(primary_key=True, default=uuid4)


class IntPrimaryKeyMixin:
    """Adds an integer primary key column named ``id``.

    The column is auto-generated by the database (typically via SERIAL/BIGSERIAL).

    Example::

        class User(AutoBase, IntPrimaryKeyMixin):
            __tablename__ = "users"
            name: Mapped[str]

        user = User(name="alice")
        user.id  # 1 (set by database on flush)
    """

    id: Mapped[int] = mapped_column(primary_key=True)
